codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true # default behavior

coverage:
  status:
    project:
      default:
        target: auto # auto compares coverage to the previous base commit
        threshold: 1% # allow for 1% reduction of coverage without failing
        base: auto # target is calculated from base commit
    patch:
      default:
        target: auto # coverage target for patches

ignore:
  - "cmd/cli/**/*" # Ignore everything under cmd/cli
  - "cmd/main.go" # Ignore the main entry point
  - "cmd/*_test.go" # Ignore test files in cmd directory

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: true # [true :: must have a base report to post]
  require_head: true # [true :: must have a head report to post]
  hide_project_coverage: false # show coverage on the git diff and project coverage
