# https://taskfile.dev

version: "3"

vars:
  GO_MODULE: github.com/klauern/gopher-tower
  GO_FILES: '$(find . -type f -name "*.go" -not -path "./frontend/*")'
  ROOT_DIR: "{{.TASKFILE_DIR}}"
  FRONTEND_DIST: internal/static/frontend # Frontend distribution directory

tasks:
  default:
    deps: [help]

  help:
    desc: Display available tasks
    cmds:
      - task --list
    silent: true

  clean:
    desc: Clean up build artifacts and temporary files
    cmds:
      - rm -rf gopher-tower
      - rm -rf {{.FRONTEND_DIST}}
      - rm -rf frontend/.next frontend/out
      - rm -f cmd/schema.sql
      - rm -f internal/db/schema.sql

  # Shared preparation tasks
  prepare:frontend:
    desc: Build and prepare frontend files for embedding
    cmds:
      - task: frontend:build
      - mkdir -p {{.FRONTEND_DIST}}
      - cp -r frontend/out/* {{.FRONTEND_DIST}}/

  prepare:
    deps:
      - prepare:frontend

  prepare:schema:
    desc: Handle database schema setup
    cmds:
      - mkdir -p internal/db/migrations
    deps:
      - go:generate

  # Frontend Tasks
  frontend:install:
    desc: Install frontend dependencies
    dir: frontend
    cmds:
      - npm install --no-audit
    sources:
      - frontend/package.json
      - frontend/package-lock.json
    generates:
      - frontend/node_modules/**/*

  frontend:build:
    desc: Build frontend for production
    dir: frontend
    cmds:
      - npm run build
    deps: [frontend:install]

  frontend:dev:
    desc: Start frontend development server
    dir: frontend
    cmds:
      - npm run dev
    deps: [frontend:install]

  frontend:test:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - npm run test
    deps: [frontend:install]

  frontend:test:watch:
    desc: Run frontend tests in watch mode
    dir: frontend
    cmds:
      - npm run test:watch
    deps: [frontend:install]

  frontend:test:coverage:
    desc: Run frontend tests with coverage report
    dir: frontend
    cmds:
      - npm run test:coverage
    deps: [frontend:install]

  frontend:lint:
    desc: Lint frontend code
    dir: frontend
    cmds:
      - npm run lint
    deps: [frontend:install]

  frontend:fmt:
    desc: Format frontend code
    dir: frontend
    cmds:
      - npx next lint --fix
    deps: [frontend:install]

  # Go Tasks
  go:deps:
    desc: Install Go dependencies
    cmds:
      - go mod download
      - go mod tidy

  go:generate:
    desc: Generate Go code (mocks, etc.)
    deps: [go:deps]
    cmds:
      - go generate ./...

  go:build:
    desc: Build Go application
    deps: [go:deps, go:generate, prepare:schema]
    cmds:
      - go build -o gopher-tower ./cmd

  go:dev:
    desc: Run Go application in development mode
    deps: [go:deps, go:generate]
    cmds:
      - go run ./cmd/main.go

  go:test:
    desc: Run Go tests
    deps: [go:deps, go:generate, prepare:schema]
    cmds:
      - go test -v ./...

  go:lint:
    desc: Lint Go code
    deps: [go:deps]
    cmds:
      - go vet ./...

  go:fmt:
    desc: Format Go code
    cmds:
      - gofmt -s -w .

  # Main workflow tasks
  build:
    desc: Build single binary with embedded frontend assets
    cmds:
      - task: clean
      - task: prepare:frontend
      - task: prepare:schema
      - task: go:build
      - echo "Build completed successfully"

  dev:
    desc: Start development environment (frontend + backend)
    deps: [go:deps, frontend:install]
    cmds:
      - ./scripts/dev.sh

  # Test tasks
  test:
    desc: Run all tests
    cmds:
      - task: test:go
      - task: test:frontend

  test:go:
    desc: Run Go tests
    cmds:
      - task: go:test

  test:frontend:
    desc: Run frontend tests
    cmds:
      - task: frontend:test

  test:watch:
    desc: Run all tests in watch mode
    cmds:
      - task: test:go:watch
      - task: test:frontend:watch

  test:go:watch:
    desc: Run Go tests in watch mode
    cmds:
      - watchexec -e go "task test:go"

  test:frontend:watch:
    desc: Run frontend tests in watch mode
    cmds:
      - task: frontend:test:watch

  test:coverage:
    desc: Run all tests with coverage
    cmds:
      - task: test:go:coverage
      - task: test:frontend:coverage

  test:go:coverage:
    desc: Run Go tests with coverage
    deps: [go:deps, go:generate]
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  test:frontend:coverage:
    desc: Run frontend tests with coverage
    cmds:
      - task: frontend:test:coverage

  # Format and lint tasks
  fmt:
    desc: Format all code
    cmds:
      - task: go:fmt
      - task: frontend:fmt

  lint:
    desc: Lint all code
    cmds:
      - task: go:lint
      - task: frontend:lint

  # Docker tasks
  docker:prepare:
    desc: Prepare assets for Docker build
    deps: [prepare:frontend, prepare:schema]
    cmds:
      - echo "Docker build preparation completed"

  docker:build:
    desc: Build all Docker images
    deps: [docker:prepare]
    cmds:
      - docker-compose build

  docker:build:multiplatform:
    desc: Build Docker images for multiple platforms (amd64, arm64)
    deps: [docker:prepare]
    cmds:
      - |
        echo "Building multi-platform Docker images..."
        # Remove existing builder if it exists
        docker buildx rm multiplatform-builder || true
        # Create a new builder instance
        docker buildx create --name multiplatform-builder --use
        # Bootstrap the builder with multi-platform support
        docker buildx inspect --bootstrap
        # Build for multiple platforms
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag gopher-tower:latest \
          --output type=image,push=false \
          .
        echo "Multi-platform build completed"

  docker:up:
    desc: Start all Docker containers
    cmds:
      - docker-compose up -d

  docker:down:
    desc: Stop all Docker containers
    cmds:
      - docker-compose down

  docker:logs:
    desc: Show logs from all containers
    cmds:
      - docker-compose logs -f

  docker:clean:
    desc: Clean up Docker resources (containers, images)
    cmds:
      - docker-compose down --rmi local
      - docker system prune -f
