// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type ActivityLog struct {
	ID         string
	Action     string
	EntityType string
	EntityID   string
	Details    sql.NullString
	CreatedAt  time.Time
	UserID     string
}

type Attachment struct {
	ID        string
	Filename  string
	FilePath  string
	FileSize  int64
	MimeType  string
	CreatedAt time.Time
	TaskID    sql.NullString
	JobID     sql.NullString
}

type Comment struct {
	ID        string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	TaskID    string
}

type Job struct {
	ID          string
	Name        string
	Description sql.NullString
	Status      string
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OwnerID     sql.NullString
}

type Notification struct {
	ID            string
	Type          string
	Content       string
	IsRead        sql.NullBool
	CreatedAt     time.Time
	UserID        string
	ReferenceID   sql.NullString
	ReferenceType sql.NullString
}

type Task struct {
	ID          string
	Title       string
	Description sql.NullString
	Status      string
	Priority    sql.NullString
	DueDate     sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      sql.NullString
	JobID       sql.NullString
}

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	FullName     sql.NullString
	Role         sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastLogin    sql.NullTime
}
