name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: task go:deps frontend:install

      - name: Build frontend
        run: task frontend:build

      - name: Prepare frontend for embedding
        run: |
          mkdir -p internal/static/frontend
          cp -r frontend/.next/static internal/static/frontend/
          cp -r frontend/public/* internal/static/frontend/ || true

      - name: Build application
        run: task build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gopher-tower
          path: |
            gopher-tower
            internal/static/frontend/
