name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build application
        run: task build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gopher-tower
          path: |
            gopher-tower
            internal/static/frontend/
